/**
 * Gain Stage Doctor (W3) orchestration.
 *
 * Analysis is deliberately separate from mutation. Rendering, decoding, measuring and
 * proposing trims are read-only with respect to the Live Set. A caller must present
 * that proposal and explicitly call {@link applyGainStageDoctor} to write it.
 */

import { badInput, staleReference } from '../errors.js';
import type { DeviceParamInfo } from '../dtos.js';
import type { LiveBridge } from '../live-bridge.js';
import type { ParamId, TrackId } from '../ids.js';
import { analyzeLoudness, dbToParamValue, suggestTrimDb } from '../transforms/loudness.js';

/** An injected WAV decoder, keeping core independent from filesystem/audio packages. */
export type DecodeWav = (wavPath: string) => Promise<Float32Array[]>;

/** Tracks and target RMS level selected before read-only analysis. */
export interface GainStageDoctorArgs {
  readonly trackIds: readonly TrackId[];
  readonly targetDb: number;
}

/** A rendered measurement common to both proposed and intentionally skipped rows. */
export interface GainStageMeasurement {
  readonly trackId: TrackId;
  readonly track: string;
  readonly peakDb: number;
  readonly rmsDb: number;
  readonly crest: number;
  readonly trimDb: number;
}

/** A finite proposed fader change, guarded by both opaque track and parameter refs. */
export interface GainStageProposedTrim extends GainStageMeasurement {
  readonly status: 'proposed';
  readonly volumeParamId: ParamId;
  readonly proposedValue: number;
}

/** Silence is measured and displayed, but is deliberately never sent to a fader. */
export interface GainStageSilence extends GainStageMeasurement {
  readonly status: 'silence';
}

/** A reviewable row generated by read-only analysis. */
export type GainStageProposal = GainStageProposedTrim | GainStageSilence;

/** Immutable plan supplied to the explicit apply step. */
export interface GainStageAnalysis {
  readonly targetDb: number;
  readonly proposals: readonly GainStageProposal[];
}

/** Result of an explicit apply attempt. */
export interface GainStageApplyResult {
  readonly appliedCount: number;
}

const DEFAULT_RENDER_BEATS = 4;

/**
 * Render, decode and measure selected tracks without mutating the Set. The returned
 * plan is not a capability to bypass review: apply re-resolves every proposed target
 * before it opens its sole transaction.
 */
export async function analyzeGainStageDoctor(
  bridge: LiveBridge,
  args: GainStageDoctorArgs,
  decode: DecodeWav,
): Promise<GainStageAnalysis> {
  if (!Number.isFinite(args.targetDb)) {
    throw badInput('Gain Stage targetDb must be finite.');
  }

  const proposals: GainStageProposal[] = [];
  for (const trackId of args.trackIds) {
    const { startBeat, endBeat } = deriveRenderRange(bridge, trackId);
    const render = await bridge.renderTrack(trackId, startBeat, endBeat);
    const { peakDb, rmsDb, crest, isSilent } = analyzeLoudness(await decode(render.path));

    // A silent render must be visible in review, but never interpreted as a request to
    // boost a fader to its upper rail.
    if (isSilent) {
      proposals.push({
        trackId,
        track: render.track,
        peakDb,
        rmsDb,
        crest,
        trimDb: 0,
        status: 'silence',
      });
      continue;
    }

    const trimDb = suggestTrimDb(rmsDb, args.targetDb);
    const volume: DeviceParamInfo = (await bridge.getTrackMixer(trackId)).volume;
    const proposedValue = dbToParamValue(trimDb, volume);
    if (!Number.isFinite(proposedValue)) {
      throw badInput('Gain Stage produced a non-finite mixer value.');
    }
    proposals.push({
      trackId,
      track: render.track,
      peakDb,
      rmsDb,
      crest,
      trimDb,
      status: 'proposed',
      volumeParamId: volume.id,
      proposedValue,
    });
  }
  return { targetDb: args.targetDb, proposals };
}

/**
 * Apply a previously reviewed plan. This re-resolves each track mixer before the one
 * write transaction, so a deleted/replaced track or changed volume target fails closed
 * before any mixer write happens.
 */
export async function applyGainStageDoctor(
  bridge: LiveBridge,
  analysis: GainStageAnalysis,
): Promise<GainStageApplyResult> {
  validateReviewedPlan(analysis);
  const targets: { readonly volumeParamId: ParamId; readonly proposedValue: number }[] = [];
  for (const proposal of analysis.proposals) {
    if (proposal.status !== 'proposed') continue;
    const freshVolume = (await bridge.getTrackMixer(proposal.trackId)).volume;
    if (freshVolume.id !== proposal.volumeParamId) {
      throw staleReference(
        proposal.trackId,
        'The Gain Stage plan no longer targets this track’s current mixer volume. Re-analyze first.',
      );
    }
    if (proposal.proposedValue < freshVolume.min || proposal.proposedValue > freshVolume.max) {
      throw badInput('Gain Stage plan contains a mixer value outside the current parameter range.');
    }
    targets.push({ volumeParamId: freshVolume.id, proposedValue: proposal.proposedValue });
  }

  if (targets.length > 0) {
    await bridge.transaction(() =>
      Promise.all(
        targets.map((target) => bridge.setParam(target.volumeParamId, target.proposedValue)),
      ),
    );
  }
  return { appliedCount: targets.length };
}

/** Validate untrusted reviewed-plan numbers before any bridge read or write. */
function validateReviewedPlan(analysis: GainStageAnalysis): void {
  if (!Number.isFinite(analysis.targetDb)) {
    throw badInput('Gain Stage plan contains a non-finite target level.');
  }
  for (const proposal of analysis.proposals) {
    if (
      !Number.isFinite(proposal.peakDb) ||
      !Number.isFinite(proposal.rmsDb) ||
      !Number.isFinite(proposal.crest) ||
      !Number.isFinite(proposal.trimDb)
    ) {
      throw badInput('Gain Stage plan contains a non-finite measurement or trim.');
    }
    if (proposal.status === 'proposed' && !Number.isFinite(proposal.proposedValue)) {
      throw badInput('Gain Stage plan contains a non-finite mixer value.');
    }
  }
}

/** Derive a non-empty Arrangement render window from arrangement clip extents. */
function deriveRenderRange(
  bridge: LiveBridge,
  trackId: TrackId,
): { readonly startBeat: number; readonly endBeat: number } {
  let start = Number.POSITIVE_INFINITY;
  let end = Number.NEGATIVE_INFINITY;
  for (const clip of bridge.listClips(trackId)) {
    if (clip.location !== 'arrangement') continue;
    if (clip.startTime < start) start = clip.startTime;
    if (clip.endTime > end) end = clip.endTime;
  }
  if (!Number.isFinite(start) || !Number.isFinite(end) || !(end > start)) {
    return { startBeat: 0, endBeat: DEFAULT_RENDER_BEATS };
  }
  return { startBeat: start, endBeat: end };
}
